### ISSUE TITLE
Build progress state for new stories

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/addon-visual-tests#237]
From AP-4227

![image](https://github.com/chromaui/addon-visual-tests/assets/1123119/262fd3ce-0fa9-4de8-afc9-4d2002fedeb0)

I kicked off a build but because the story list is so long I can't see progress and the state being shown on this particular story is also confusing

**Comment by MichaelArestad** [comment]
[The UI of the addon panel should change to show the following](https://www.figma.com/file/GFEbCgCVDtbZhngULbw2gP/Visual-Tests-addon-for-Storybook?type=design&node-id=6980%3A151447&mode=design&t=4sdkrDieWJEj31Mo-1):

![image](https://github.com/chromaui/addon-visual-tests/assets/1123119/b5a2c8cc-836c-4cc9-9d41-23f21ecfedbf)

The other loading states didn't quite make sense here so I put together a new state (similar to others).
