### ISSUE TITLE
SidebarBottom: create story for visual test coverage

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/addon-visual-tests#239]
From AP-4238

This isn't a bug per se but a requirement to finish the project. Storybook allows VTA to drop in an arbitrary component in the sidebar. 

We have no coverage of this in the VTA project which makes it hard to test or adjust. I'd expect to see a story for SidebarBottom in our project.

#### 
<img width="266" alt="image" src="https://github.com/chromaui/addon-visual-tests/assets/22988955/7e971e3d-b573-46bb-b0e4-417d98ec2b70">

Assigning "high" priority because it's a straightforward update which also unblocks a related bug from  AP-4114

**Comment by jonniebigodes** [comment]
Comments from mentioned ticket:
> @domyen This Sidebar Bottom is a Manager API from SB core. Do we want that to be a standard height no matter the integration? I will coordinate with SB team if so.
> via @thafryer 

>Agree that it seems like a Storybook API issue!

>Yes that'd be helpful to have a standard height. We want it to align with the standard bottom bar in Storybook addons. 

>I did more investigation and saw that the CSS is set in an unexpected way for this element.
> via @domyen 

>Because it is effectively a toolbar, the height of the filter container should be 40px + border size.
>via @MichaelArestad 

>I think this one has been resolved. Will reopen if I see it again.
> via @MichaelArestad
