### ISSUE TITLE
Can't stop a test

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/addon-visual-tests#241]
From AP-4247

When I start a test and wait for the test to get to the "Testing stories" step, I can't stop a test. I am able to start and stop tests on the previous steps (Building, uploading). As you might notice, the expanded description also doesn't match. I'll do some digging to see when that bug started.

<img width="1231" alt="disable-tests" src="https://github.com/chromaui/addon-visual-tests/assets/22988955/e8538d0d-a8a8-41fc-9984-0ab7f0ca01bb">

**Comment by MichaelArestad** [comment]
Here is a proposal of what we should do when a user clicks at a stage we can no longer interrupt:

![image](https://github.com/chromaui/addon-visual-tests/assets/1123119/10e0aff5-a95e-413c-b9c5-3e000c18df75)

[And here is the source document](https://www.figma.com/file/GFEbCgCVDtbZhngULbw2gP/Visual-Tests-addon-for-Storybook?type=design&node-id=7368%3A231823&mode=design&t=7NPALvZIwc3KZxXK-1)
