### ISSUE TITLE
Progress bar shouldn't automatically expand

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/addon-visual-tests#245]
From AP-4318

#### How is the user affected? And what is the expected behavior?

When I start and stop a test, the progress bar in the VTA panel automatically expands. Video demo:

https://github.com/chromaui/addon-visual-tests/assets/22988955/f4a87dc0-358f-46ce-ace5-35cef2c38108

#### How many and/or what class of users does this impact? 

Anyone who stops a test.

#### Is there a workaround? 

Not that I am aware of.

#### What are the steps for reproducing the issue? 

1. Start a test.
2. Stop a test.
3. Repeat as necessary

**Comment by MichaelArestad** [comment]
Comment from @ghengeveld on the original ticket:
> The reason this auto-expands is because it reveals build errors, specifically the step which failed. In case of build cancellation this doesn't make sense because it was intentional and the panel doesn't reveal any more information. So I think we should just not auto-expand on cancellation but we should on error.
