### ISSUE TITLE
Onboarding shows wrong screen

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/addon-visual-tests#246]
From AP-4342

#### How is the user affected? And what is the expected behavior?

After running my first build in a fresh project as part of the "happy path" onboarding (Storybook `8.0.0-rc.2`, VTA `1.2.7`, I see the following screen:

![image](https://github.com/chromaui/addon-visual-tests/assets/1123119/0884f73b-07ab-4082-8d67-46e5b9cc5862)

The contents of the addon panel look wrong to me. I would expect it to say something to the effect of "congrats on running your first build, now let's check out the changes. Next >".

When I click the "Done" button, it takes me to the next step of the tour--which is blocked by the "Storybook 8 enters beta" notification. A separate bug, I think.

#### How many and/or what class of users does this impact? 

All VTA users? I'm not sure.

#### Is there a workaround? 

Yes, if you click "Done" it will take you to the next step of the tour.

#### What are the steps for reproducing the issue? 

To get to this step, I:

1. Created an empty directory
2. Ran `npx storybook`@next` init` in the directory and selected `react-vite-ts` option
3. Set up git
4. Ran through the onboarding
5. Changed the story text of the Button.Secondary story to "Buttoon"
6. Ran my first build

**Comment by MichaelArestad** [comment]
[This is how that view should look](https://www.figma.com/file/GFEbCgCVDtbZhngULbw2gP/Visual-Tests-addon-for-Storybook?type=design&node-id=2907%3A192798&mode=design&t=qbBh4wnabezcV0SS-1). The copy needs to be updated:

![image](https://github.com/chromaui/addon-visual-tests/assets/1123119/9b9b4c74-b653-4cf2-b883-b2e2581e1ae1)

It looks like the design you are seeing in the issue above should only be visible to users who already completed onboarding once.

**Comment by shilman** [comment]
Possible duplicate to #252 ?

**Comment by ghengeveld** [comment]
@MichaelArestad This looks like you're not in the onboarding state (you skipped/finished the walkthrough already). The `vtaOnboarding` query param may not be sufficient. You can reset it through the [API](https://www.chromatic.com/api) like so:

```gql
mutation {
  updateUserPreferences(input: { vtaOnboarding: UNSET }) {
    updatedPreferences {
      vtaOnboarding
    }
  }
}
```

**Comment by MichaelArestad** [comment]
@ghengeveld Does that mean our users won't see this?

**Comment by ghengeveld** [comment]
I just verified, this is what I see on a clean project after running the first build:

<img width="508" alt="Screenshot 2024-04-04 at 17 42 20" src="https://github.com/chromaui/addon-visual-tests/assets/321738/3f73aa5b-e74a-4adc-8dc1-d271dea9ae2d">

This looks like the correct screen to me.

**Comment by ghengeveld** [comment]
I opened #283 to fix the background color on the thumbnail container (the image should be on a white background, not transparent).
