### ISSUE TITLE
Ensure VTA panel opens when clicking "run tests" button in warning state

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/addon-visual-tests#253]
As discussed below, rather than hiding the "run tests" button when there's an issue, make sure that it opens the Visual Tests panel. Currently this doesn't work when on a docs page, as there is no addons panel in this situation.

**Comment by shilman** [comment]
I'd argue this is a conversion feature. Possibly annoying to users but good for discoverability.

**Comment by ghengeveld** [comment]
Already implemented (hiding button when there's an issue). Showing a warning state out of the box is not a good look.

**Comment by ghengeveld** [comment]
This is the current state of the button while onboarding:

<img width="466" alt="Screenshot 2024-05-07 at 11 30 13" src="https://github.com/chromaui/addon-visual-tests/assets/321738/48ff083d-d533-47da-9c61-db88c044ec7b">

<img width="464" alt="Screenshot 2024-05-07 at 11 29 16" src="https://github.com/chromaui/addon-visual-tests/assets/321738/0c5b4002-00bb-435f-a709-0c890b5dc59e">

I agree with @shilman that this is okay for discoverability.

However, I did also encounter this issue, which happens when restarting Storybook after the initial setup in a monorepo:

<img width="464" alt="Screenshot 2024-05-07 at 11 32 58" src="https://github.com/chromaui/addon-visual-tests/assets/321738/8699bd5d-3540-4a52-b900-6e8163443935">

The configuration file that's generated currently does not automatically include any of the suggested configuration fixes. I think we should fix that, so the autogenerated config file includes those suggestions.

**Comment by MichaelArestad** [comment]
I am on the fence with this one. I see it as potentially an avenue for discoverability, but we may want to change from a tooltipNote to something this actionable. For example, we could possibly show a full tooltipMessage with a button that either takes the user through the login flow or takes the user to the addon panel project selection.

**Comment by ghengeveld** [comment]
The config issue has been addressed in #306, so this is no longer a problem out of the box.

I'm going to keep the button state as-is, for sake of discoverability. I would hate for the VTA to go unnoticed because it's not configured / the user isn't signed in. The dot isn't obtrusive so even if people leave it like that it doesn't get in the way.

The button already opens the VTA panel, which then contains more details about the problem (or simply prompts for what it needs). I don't think a more elaborate tooltip is worthwhile.

Here's what I'll do (as part of this ticket):
- Make sure that clicking the button opens the VTA, i.e. switch to the next/first story when on a docs page.
- Add telemetry for the click.
