### ISSUE TITLE
Track when a project is successfully linked via VTA

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/addon-visual-tests#254]
From AP-4402

### What

We currently track:

1. When a user Signs In *and* Signs Ups to Chromatic from VTA
2. When a project has a build from VTA

There is not close to a 100% conversion from step 1 to step 2. We are missing an important data point in between these two steps of a user successfully linking their project.

This data should show up in BigQuery so we can query this in Looker.

Note: Investigate how tracking works for `create project` , and how this should be tagged specifically if the project is created through VTA (and confirm how tracking for linking a project would be affected \[it likely shouldn't\])

### Why

This will help us understand where user drop-off points are, and properly prioritize future work for VTA

### How

Would this only be client-side?

**Comment by shilman** [comment]
Superceded by Notion doc
