### ISSUE TITLE
Include link to VTA on "Sign in" page

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/addon-visual-tests#258]
From AP-4118

#### What

For users that have VTA setup on their project, but aren't familiar with how/why it works, add a "Learn more" link to goes to the VTA marketing landing page.

**Why**

The use case I'm thinking of is when a tech lead sets up a project and an engineer, who might not be familiar with it, tries it out themselves for the first time.

<img width="376" alt="image (4)" src="https://github.com/chromaui/addon-visual-tests/assets/321738/37e4ad08-b2bc-4141-b499-e8932a31be26">

**Comment by MichaelArestad** [comment]
We need to add a "toolbar" as shown in the onboarding mockups. [In the prototype](https://www.figma.com/file/GFEbCgCVDtbZhngULbw2gP/Visual-Tests-addon-for-Storybook?type=design&node-id=2907%3A191572&mode=design&t=qbBh4wnabezcV0SS-1), the action button on the top right links to the Visual Tests marketing website. It should look like this:
![image](https://github.com/chromaui/addon-visual-tests/assets/1123119/0b49a504-a654-4a5e-b920-09a193523f56)
