### ISSUE TITLE
Stories with `parameters.chromatic.disable: true` show "New story found"

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/addon-visual-tests#294]
### Describe the bug

Stories where Chromatic is explicitly disabled will always show the "New story found" screen. Running a build will not snapshot it and thus continue to show this screen. There should be an explanation that the current story is disabled for Chromatic.

### To reproduce

Create a story like this:
```
export const ChromaticDisabled = {
  parameters: {
    chromatic: { disable: true }
  }
}
```

Open the Visual Tests panel on this story, it will show this screen:

<img width="674" alt="Screenshot 2024-04-28 at 12 28 35" src="https://github.com/chromaui/addon-visual-tests/assets/321738/df12a71b-b476-42e8-943a-404d549c7ea1">

Run a build and confirm it continues to show this screen.

### Environment

Storybook v8.0.9 for Next.js.
Visual Tests addon v1.3.3.

**Comment by shilman** [comment]
@ghengeveld Not critical but pretty annoying! We should fix during cooldown if possible.
