### ISSUE TITLE
data-chromatic="ignore" not working correctly

### ISSUE THREAD

**Issue by jmargolisvt** [chromaui/addon-visual-tests#75]
![Screenshot 2023-09-05 at 9 27 26 AM](https://github.com/chromaui/addon-visual-tests/assets/1338941/2b05e922-4e37-4918-a4ad-de607e241d9d)

I have added `data-chromatic="ignore"` to the div that displays the date, yet I'm getting a Chromatic failure when the length of the date changes.  As the date changes, so will the width of that div and it should pass regardless because of the "ignore" tag.  For the "ignore" to be useful, it needs to ignore both value and width changes.  Here you can see that it seems to only know about the first 192.67px.

![Screenshot 2023-09-05 at 9 37 21 AM](https://github.com/chromaui/addon-visual-tests/assets/1338941/fe908632-ac7e-4989-bd27-13eb580aa9ff)
![Screenshot 2023-09-05 at 9 37 29 AM](https://github.com/chromaui/addon-visual-tests/assets/1338941/3bbd1590-e29d-4344-9eeb-7e9c6afa52bd)

**Comment by ghengeveld** [comment]
Please reach out on Intercom if you haven't already. The issue is unrelated to this repository.

**Comment by jmargolisvt** [comment]
What's intercom?  Can you provide a link, plz?

**Comment by ghengeveld** [comment]
Intercom is our chat bubble on the webapp. Also visible on e.g. the docs pages. Alternatively you can email support@chromatic.com
